idf_component_register(SRCS "main.cpp"
                    "Src/RtosUtils.cpp"
                    "Src/Leds.cpp"
                    "Src/Matrix.cpp"
                    "Src/Hid.cpp"
                    "Src/Ble.cpp"
                    "Src/esp_hid_gap.c"
                    "Src/Usb.cpp"
                    INCLUDE_DIRS "Inc")
